ARG APP_BUILD_ROOT=/opt/app-root

FROM registry.redhat.io/ubi9/go-toolset:1.26.5@sha256:f221165cd493d89c13ce384e8e58914571ea353f47a1443698d981494842ff83 AS builder

ARG TARGETOS
ARG TARGETARCH
ARG APP_BUILD_ROOT

ENV GOEXPERIMENT=strictfipsruntime
ENV APP_ROOT=$APP_BUILD_ROOT
ENV GOPATH=$APP_ROOT

WORKDIR $APP_ROOT/src/
COPY go.mod ./
COPY go.sum ./
COPY cmd/main.go cmd/main.go
COPY internal/ internal/
RUN go mod download && \
    CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} GOEXPERIMENT=${GOEXPERIMENT} go build -a -o ${APP_ROOT}/manager cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.8-1786380870@sha256:7c372902c8d211db2d25c8277ba534a73b92742a334874dced829a63b0f21221 AS deploy

ARG APP_BUILD_ROOT

WORKDIR /
COPY --from=builder ${APP_BUILD_ROOT}/manager .
COPY LICENSE /licenses/license.txt
USER 65532:65532

ENTRYPOINT ["/manager"]

LABEL com.redhat.component="odh-workload-variant-autoscaler-controller-rhel9" \
      name="rhoai/odh-workload-variant-autoscaler-controller-rhel9" \
      description="a Kubernetes controller that performs intelligent autoscaling for inference model servers based on saturation" \
      summary="odh-workload-variant-autoscaler-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="odh-workload-variant-autoscaler-controller" \
      io.k8s.description="odh-workload-variant-autoscaler-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"